onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@firebase/util'
  - '@swc/core'
  - bcrypt
  - es5-ext
  - esbuild
  - faiss-node
  - protobufjs
  - puppeteer
  - re2
  - tree-sitter
  - tree-sitter-c
  - tree-sitter-c-sharp
  - tree-sitter-cpp
  - tree-sitter-go
  - tree-sitter-java
  - tree-sitter-javascript
  - tree-sitter-python
  - tree-sitter-rust
  - tree-sitter-scala
  - tree-sitter-typescript
