// This file is auto-generated by /Users/daniel/dev/nous/frontend/scripts/env.js
export const env = {
  "version": "0.8.0",
  "API_BASE_URL": "http://localhost:3000/api/",
  "GCLOUD_PROJECT": "tg-infra-dev",
  "FIRESTORE_DATABASE": "sophia",
  "AUTH": "single_user"
};
